version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "db:/var/lib/postgresql"

  app:
    image: even_test:development
    build: .
    volumes:
      - .:/app
      - bundle:/bundle
    depends_on:
      - db
    # expose ports
    ports:
      - "3000:3000"

volumes:
  db:
  bundle:
